[project]
name = "tinymarket"
authors = []
description = ""
telemetry = false
requirements = []
cache_dir = "/Users/fg/.clarinet/cache"
boot_contracts = ["pox", "costs-v2", "bns"]
[contracts.tiny-market]
path = "contracts/tiny-market.clar"

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
